FROM node:20-alpine
WORKDIR /app

COPY package.json ./
RUN npm install --legacy-peer-deps

# Bust cache: update this label when source files change
LABEL version="4.0.1"

COPY . .

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG N8N_API_URL
ARG N8N_API_KEY
ARG N8N_WORKFLOW_ID

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV N8N_API_URL=$N8N_API_URL
ENV N8N_API_KEY=$N8N_API_KEY
ENV N8N_WORKFLOW_ID=$N8N_WORKFLOW_ID
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
